name: Techi Secrets

on: [push]

jobs:
  list:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.0

      - name: Show secrets
        run: echo "The secrets is ${{secrets.TECHI}}"
  